// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAddz0pyhaShyBLsAENMiZgFPp2zFWQ59Y',
    appId: '1:47012066504:web:ffcb8d24b6a35a2da861fd',
    messagingSenderId: '47012066504',
    projectId: 'final-project-toko-flutt-4e32a',
    authDomain: 'final-project-toko-flutt-4e32a.firebaseapp.com',
    storageBucket: 'final-project-toko-flutt-4e32a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaymTVT0cHq2ZWBKeuRc39qFnRprthgOs',
    appId: '1:47012066504:android:d21f496e99276a9da861fd',
    messagingSenderId: '47012066504',
    projectId: 'final-project-toko-flutt-4e32a',
    storageBucket: 'final-project-toko-flutt-4e32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7TiRrTlbVz_0_DzrJU3Ii_hN_eUjThi8',
    appId: '1:47012066504:ios:c4d29c3965f46589a861fd',
    messagingSenderId: '47012066504',
    projectId: 'final-project-toko-flutt-4e32a',
    storageBucket: 'final-project-toko-flutt-4e32a.appspot.com',
    iosClientId: '47012066504-bgdm6lmqc3v1ggo78gelvpk490b2jn9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAdminToko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7TiRrTlbVz_0_DzrJU3Ii_hN_eUjThi8',
    appId: '1:47012066504:ios:c4d29c3965f46589a861fd',
    messagingSenderId: '47012066504',
    projectId: 'final-project-toko-flutt-4e32a',
    storageBucket: 'final-project-toko-flutt-4e32a.appspot.com',
    iosClientId: '47012066504-bgdm6lmqc3v1ggo78gelvpk490b2jn9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAdminToko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAddz0pyhaShyBLsAENMiZgFPp2zFWQ59Y',
    appId: '1:47012066504:web:292a63e0df401315a861fd',
    messagingSenderId: '47012066504',
    projectId: 'final-project-toko-flutt-4e32a',
    authDomain: 'final-project-toko-flutt-4e32a.firebaseapp.com',
    storageBucket: 'final-project-toko-flutt-4e32a.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAddz0pyhaShyBLsAENMiZgFPp2zFWQ59Y',
    appId: '1:47012066504:web:157f59c395206b63a861fd',
    messagingSenderId: '47012066504',
    projectId: 'final-project-toko-flutt-4e32a',
    authDomain: 'final-project-toko-flutt-4e32a.firebaseapp.com',
    storageBucket: 'final-project-toko-flutt-4e32a.appspot.com',
  );
}
